#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hangman.Resource", IsApplication=true)]

namespace Hangman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::Hangman.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int CS = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int Hangman1 = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int Hangman2 = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int Hangman3 = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int Hangman4 = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int Hangman5 = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int Hangman6 = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int Hangman7 = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int mv = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int title = 2130771977;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int btnA = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int btnB = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int btnC = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int btnD = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int btnE = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int btnEasy = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int btnF = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int btnG = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int btnH = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int btnHard = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int btnI = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int btnJ = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int btnK = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int btnL = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int btnM = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int btnMedium = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int btnMusic = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int btnN = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int btnO = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int btnP = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int btnQ = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int btnR = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int btnS = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int btnT = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int btnU = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int btnV = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int btnW = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int btnX = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int btnY = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int btnZ = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int imageView1 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int ivHangman = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int linearLayout1 = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int txtGuesses = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int txtWord = 2130837538;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F040000
			public const int Theme = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F060000
			public const int xamarin_essentials_fileprovider_file_paths = 2131099648;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
